version: 0.2

phases:
  build:
    commands:
      - echo "Building with Maven..."
      - ./mvnw clean package -DskipTests
artifacts:
  files:
    - target/nflp-backend-0.0.1-SNAPSHOT. jar
    - Procfile